### ISSUE TITLE
Test fails on MySQL with IntegrityError

### ISSUE THREAD

**Issue by nrmay** [mytardis/mytardis-app-mydata#6]
A test in the app 'mydata' fails when run on a MySQL database;

- tardis/apps/mydata/tests/test_api.py", line 70, in setUp
    super(UploaderAppResourceTest, self).setUp()
- IntegrityError: (1062, "Duplicate entry '4' for key 'user_id'")

See full text below: 

 
> Creating test database for alias 'default'...
>
>S.......E...........................................................................................................S.S.S.S.S.S.S.....................S.............................S.S.S.S.S...S..................-------------------------------------------------------> ---------------
>Traceback (most recent call last):
>  File "/opt/mytardis/develop/tardis/apps/mydata/tests/test_api.py", line 70, in setUp
    super(UploaderAppResourceTest, self).setUp()
>
> ======================================================================
> ERROR: test_get_uploader_by_id (tardis.apps.mydata.tests.test_api.UploaderAppResourceTest)
>  File "/opt/mytardis/develop/tardis/apps/mydata/tests/test_api.py", line 48, in setUp
    self.user_profile = UserProfile(user=self.user).save()
 File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
   force_update=force_update, update_fields=update_fields)
 File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/mytardis/develop/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
> IntegrityError: (1062, "Duplicate entry '4' for key 'user_id'")
>
>
> FAILED (SKIP=15, errors=1)
> \----------------------------------------------------------------------
> Ran 195 tests in 22.704s
> Destroying test database for alias 'default'...

**Comment by wettenhj** [comment]
Thanks, @nrmay, I'll try to reproduce and fix the test.

**Comment by wettenhj** [comment]
@nrmay, this pull request should fix the test: https://github.com/mytardis/mytardis-app-mydata/pull/7
